# Generated by Django 3.2.5 on 2021-07-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_facebook', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=800)),
            ],
        ),
    ]
